// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJV7s8cwkRQOaDkjHBbGs9fouHQykuDM',
    appId: '1:508339142935:web:d1da6531c5ee97f3f6b752',
    messagingSenderId: '508339142935',
    projectId: 'marc-vane',
    authDomain: 'marc-vane.firebaseapp.com',
    storageBucket: 'marc-vane.firebasestorage.app',
    measurementId: 'G-0LXT07NEWF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYpT-yF7rR1RBxu85xcQm-KWXK3Ph4fC4',
    appId: '1:508339142935:ios:5a610a6161a046f4f6b752',
    messagingSenderId: '508339142935',
    projectId: 'marc-vane',
    storageBucket: 'marc-vane.firebasestorage.app',
    iosBundleId: 'com.example.arc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJV7s8cwkRQOaDkjHBbGs9fouHQykuDM',
    appId: '1:508339142935:web:bd89bb78548ea48ef6b752',
    messagingSenderId: '508339142935',
    projectId: 'marc-vane',
    authDomain: 'marc-vane.firebaseapp.com',
    storageBucket: 'marc-vane.firebasestorage.app',
    measurementId: 'G-K52YCBWYHH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpT-yF7rR1RBxu85xcQm-KWXK3Ph4fC4',
    appId: '1:508339142935:ios:6bede2b21057c1bdf6b752',
    messagingSenderId: '508339142935',
    projectId: 'marc-vane',
    storageBucket: 'marc-vane.firebasestorage.app',
    iosBundleId: 'com.marcvane.arc',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXZ7ERi9l_lPzqiZoGZsTA8BdvKaj8ew',
    appId: '1:508339142935:android:002aa749061bb32bf6b752',
    messagingSenderId: '508339142935',
    projectId: 'marc-vane',
    storageBucket: 'marc-vane.firebasestorage.app',
  );
}
